Understanding NumPy Array

In this notebook, we will examine the core ideas and features of NumPy, the essential Python library for scientific computation. The name "Numerical Python" refers to a powerful library that supports big, multi-dimensional arrays and matrices and offers a variety of mathematical functions to work with them effectively. It is a crucial tool for machine learning, scientific computing, and data analysis jobs.

In this notebook, we will cover the following key topics:
1. Arrays in NumPy: Learn about the core data structure in NumPy, the array, which allows us to represent and manipulate arrays efficiently. We will explore different ways to create arrays, perform basic operations, and access array elements.
2. Array Operations: Discover the various mathematical and logical operations that can be performed on NumPy arrays. We will explore element-wise operations, array broadcasting, and vectorized computations.
3. Indexing and Slicing: Understand how to access and manipulate specific elements, rows, or columns within NumPy arrays using indexing and slicing techniques. This will allow us to extract and modify portions of arrays efficiently.
4. Array Manipulation: Learn how to reshape, concatenate, and split arrays to transform their dimensions and structures. We will explore functions to resize, stack, and split arrays to suit our data processing needs.

By the end of this notebook, you will have a solid understanding of the core concepts of NumPy and be well-equipped to leverage its powerful features for your data analysis and scientific computing tasks.
So let's dive in and explore the world of NumPy!

In [ ]:
import numpy as np

Creating a Numpy Array

In [2]:
# Create a Numpy Array
arr1 = np.array([2,4,6,8,10])
print(arr1)

[ 2  4  6  8 10]


In [3]:
# Creat a Numpy Array using arange
arr2 = np.arange(1,21)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Array Features

In [4]:
# Creating an Array
arr3 = np.arange(1,16)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [8]:
# Check the array type
print(type(arr3))
print(arr3.dtype)

<class 'numpy.ndarray'>
int32


In [9]:
# Finding the shape of the array
arr3.shape

(15,)

Changing the data type of Numpy Arrasy

In [11]:
# Create an array
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [17]:
# Reshape the array
a = a.reshape(3,3)

In [18]:
# Change the data type
a = a.astype(float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
# Create a new array
new_a = np.arange(1,16)
print(new_a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [20]:
# Convert the Numpy Array to a Python List
new_a.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

Indexing in Array

In [29]:
# Create an Array
ind = np.arange(1,21,2)
print(ind)

[ 1  3  5  7  9 11 13 15 17 19]


In [31]:
# Return the first Item in an array
print(ind[0])

1


In [33]:
# Return the third Item in an array
print(ind[2])

5


In [34]:
# Get the last item from the array
print(ind[-1])

19


In [35]:
# Get the third and last item in an array and add them up
print(ind[2] + ind[-1])

24


Slicing Numpy Array

In [21]:
# Create an Array
new_b = np.arange(1,21)
print(new_b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [22]:
# Slice the array to return the first 5 items of the array
new_b[0:5]

array([1, 2, 3, 4, 5])

In [24]:
# Slice the array to return items in index 7,8 and 9
new_b[6:9]

array([7, 8, 9])

In [25]:
# Return all the items in the array starting with index 5
new_b[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
# Return the items in the array from index 0 with a step of 3
new_b[0::3]

array([ 1,  4,  7, 10, 13, 16, 19])

In [27]:
# Multiply an array by 2
new_b*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

Copy and viewing and Numpy array

In [36]:
# Create an array
c_v = np.arange(1,30,4)
print(c_v)

[ 1  5  9 13 17 21 25 29]


In [39]:
# Copy the array
copy = c_v.copy()
print('The copied array is:', copy)
print('The original array is:',c_v)

The copied array is: [ 1  5  9 13 17 21 25 29]
The original array is: [ 1  5  9 13 17 21 25 29]


In [43]:
# view the array
view = c_v.view()
print('The view array is:', view)
print('The original array is:',c_v)

The view array is: [ 1  5  9 13 17 21 25 29]
The original array is: [ 1  5  9 13 17 21 25 29]


In [41]:
# Copy the array and change the value of the second item content
copy2 = c_v.copy()
copy2[1] = copy2[1]*3
print('The copied array is:', copy2)
print('The original array is:',c_v)

The copied array is: [ 1 15  9 13 17 21 25 29]
The original array is: [ 1  5  9 13 17 21 25 29]


In [ ]:
# Check the base of the array

In [45]:
print('The base of the copied data is: ', copy2.base)
print('The base of the Views data is: ', view.base)

The base of the copied data is:  None
The base of the Views data is:  [ 1  5  9 13 17 21 25 29]


Iterating through an Array

In [47]:
# Create an array
iter1 = np.arange(5,27,3)
print(iter1)

[ 5  8 11 14 17 20 23 26]


In [48]:
# Iterate through the array
for x in iter1:
    print(x)

5
8
11
14
17
20
23
26


In [51]:
# Iterate through the array and return only the even numbers
for x in iter1:
    if x%2==0:
        print(x)

8
14
20
26


In [53]:
# Iterate through the array and return only the odd numbers
for x in iter1:
    if x%2!=0:
        print(x)

5
11
17
23


Joining a Numpy Array

In [61]:
# Create two array
j_arr1 = np.arange(2,11,2)
j_arr2 = np.arange(1,11,3)

In [62]:
joined_arr = np.concatenate((j_arr1,j_arr2))

In [63]:
print(joined_arr)

[ 2  4  6  8 10  1  4  7 10]


Spliting a Numpy Array

In [65]:
# Create an array
split_arr = np.arange(1,21)
print(split_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [66]:
# Split the array into 3
np.array_split(split_arr,3)

[array([1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19, 20])]

In [67]:
# Split the array into 4
np.array_split(split_arr, 4)

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

Search a Numpy Array

In [68]:
# Create an Array
sear_arr = np.arange(1,11)
print(sear_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [70]:
# Gett the index position of item number 7
print(np.where(sear_arr==7))

(array([6], dtype=int64),)


In [71]:
# Get the index position of items that are divisible by 2
np.where(sear_arr%2==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

Sorting a Numpy Array

In [75]:
# Create an Array
sort_arr = np.array([1,21,6,9,11,15,8,5])
print(sort_arr)

[ 1 21  6  9 11 15  8  5]


In [77]:
# Sort the array
print(np.sort(sort_arr))

[ 1  5  6  8  9 11 15 21]


In [78]:
# Create an array
sort_arr2 = np.array(['Yam', 'Banana', 'Mango', 'Fish'])
print(sort_arr2)

['Yam' 'Banana' 'Mango' 'Fish']


In [79]:
# Sort the array
np.sort(sort_arr2)

array(['Banana', 'Fish', 'Mango', 'Yam'], dtype='<U6')